@startuml 並列処理
title カレー作成
start
:具剤買いに行く;
:鍋を用意する;
fork
:具剤を用意する;
fork
:玉ねぎを切る;
fork again
:大豆を程よいサイズにすりつぶす;
fork again
:ひき肉を解凍する;
fork again
:鍋を温める;
end fork
:具剤を鍋に入れる;
:カレー粉末と具剤を絡めて炒める;
:お湯を入れて煮る;
:カレールーとスパイスを入れる;
fork again
:炊飯器の電源を入れる;
:米を洗う;
:米を炊く;

end fork
:盛り付ける;
:キーマカレー]
stop
@enduml