@startuml
left to right direction
object "<u>A: 客クラス</u>" as k0 {
チェックイン日：五月三日
}
object "<u>B: 客クラス</u>" as k1 {
チェックイン日：五月三日
}
object "<u>３０１: 部屋クラス</u>" as k2 {
タイプ：シングル
宿泊料：１１,０００
キャンペーン価格：９０００

}
object "<u>３０２: 部屋クラス</u>" as k4 {
    タイプ：シングル
宿泊料：１１,０００
キャンペーン価格：９０００
}
object "<u>３０３: 部屋クラス</u>" as k3 {
    タイプ：シングル
宿泊料：１１,０００
キャンペーン価格：９０００
}
object "<u>ホテル: ホテルクラス</u>" as k5 {
部屋
}
k0--k2
k5--k2
k5--k3
k5--k4
k1--k3