@startuml
hide footbox
Actor "<u>:客</u>" as a1
participant "<u>:料金装置</u>" as a2
participant "<u>:ボタン</u>" as a3
participant "<u>:ベンダー</u>" as a4
mainframe sd 自動販売機

activate a1
a1-->a2:料金投入
     activate a2
a1<--a2:投入金額表示
     deactivate a2
 a1-->a3:ドリンク選択
     activate a3
 a3-->a4:ドリンク種類伝達
     deactivate a3
 activate a4

 a1<--a4:ドリンク引き渡し
@enduml