@startuml 
left to right direction

[*] --> 待機中: 電源オン
待機中-->[*] :　電源オフ
待機中->印刷中: 印刷
待機中<-印刷中: 印刷完了
印刷中->用紙無し: 用紙切れ
印刷中<-用紙無し: 用紙補充
' 待機中--> 印刷中: 待機完了
' 印刷中->c
' c--> 用紙無し: 用紙がなくなる
' 用紙無し--> [*] 
' c--> [*] :　印刷完了
@enduml