@startuml 例題1
left to right direction
actor 利用者 as user
actor 看護師 as nace
rectangle 診察予約システム {
usecase 予約する as a1
usecase 自分の順番を確認する as a2
usecase 順番を取り消す as a3
usecase 今の番号を確認する as a4
}
user-->a1
user-->a2
user-->a3
a4<--nace
user-->a4
@enduml